"""
Competency schemas.

The Competency is the central domain model of this system.
Every question, evaluation, and recommendation maps to a competency.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class PriorityEnum(str, Enum):
    """Priority level for skill gaps and recommendations."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Competency(BaseModel):
    """
    Represents a single competency node in the knowledge graph.

    Competencies are hierarchical. A parent competency (e.g., Python)
    can have children (e.g., OOP, Async, Libraries). Every question
    is mapped to exactly one competency. Every evaluation updates
    the confidence score of that competency.
    """

    model_config = ConfigDict(frozen=False, validate_assignment=True)

    id: str = Field(
        ...,
        description="Unique competency identifier e.g. comp_python_oop",
    )
    name: str = Field(
        ...,
        description="Human-readable competency name e.g. Object Oriented Programming",
    )
    description: str = Field(
        ...,
        description="What this competency covers and why it matters",
    )
    parent_id: Optional[str] = Field(
        default=None,
        description="Parent competency id for hierarchy, null if root",
    )
    children: list[str] = Field(
        default_factory=list,
        description="List of child competency ids",
    )
    role_relevance: dict[str, float] = Field(
        default_factory=dict,
        description="Map of job role to relevance weight 0.0-1.0",
    )
    difficulty_level: str = Field(
        default="intermediate",
        description="Overall difficulty: beginner, intermediate, advanced",
    )
    required_concepts: list[str] = Field(
        default_factory=list,
        description="Concepts that must appear in a correct answer",
    )
    related_resources: list[str] = Field(
        default_factory=list,
        description="Resource ids relevant to this competency",
    )
    confidence_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Current user confidence 0.0 to 1.0",
    )
    evidence_count: int = Field(
        default=0,
        ge=0,
        description="Number of times this competency was assessed",
    )
    elo_rating: float = Field(
        default=1000.0,
        description="Elo-style skill rating for adaptive engine",
    )
    last_assessed: Optional[datetime] = Field(
        default=None,
        description="Timestamp of the last assessment",
    )
    improvement_trend: float = Field(
        default=0.0,
        description="Positive means improving, negative means declining",
    )


class CompetencyScore(BaseModel):
    """
    Represents the current competency score record for a user.

    Stored in the database competency_scores table.
    Updated after every evaluation.
    """

    model_config = ConfigDict(frozen=False)

    user_id: int = Field(..., description="User who owns this score")
    competency_id: str = Field(..., description="Which competency")
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence score 0.0 to 1.0",
    )
    elo_rating: float = Field(
        default=1000.0,
        description="Current Elo rating for adaptive difficulty",
    )
    evidence_count: int = Field(
        default=0,
        description="Total number of evaluated answers",
    )
    last_assessed: Optional[datetime] = Field(
        default=None,
        description="When was this last updated",
    )
    improvement_trend: float = Field(
        default=0.0,
        description="Recent improvement rate",
    )


class CompetencyUpdate(BaseModel):
    """
    Represents a single competency confidence update after evaluation.

    Generated by the confidence updater and logged for transparency.
    """

    model_config = ConfigDict(frozen=True)

    competency_id: str = Field(..., description="Which competency was updated")
    old_confidence: float = Field(..., description="Confidence before evaluation")
    new_confidence: float = Field(..., description="Confidence after evaluation")
    old_elo: float = Field(..., description="Elo rating before evaluation")
    new_elo: float = Field(..., description="Elo rating after evaluation")
    evidence_added: str = Field(
        ...,
        description="Summary of what evidence triggered this update",
    )
    delta: float = Field(
        ...,
        description="Change in confidence score",
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When this update occurred",
    )


class CompetencyGap(BaseModel):
    """
    Represents a detected skill gap for a specific competency.

    Generated by the skill gap analyzer after each session.
    Used by the recommendation engine to prioritize learning.
    """

    model_config = ConfigDict(frozen=True)

    competency_id: str = Field(..., description="Competency with identified gap")
    competency_name: str = Field(..., description="Human-readable name")
    current_confidence: float = Field(..., description="Current confidence 0.0-1.0")
    required_confidence: float = Field(
        default=0.7,
        description="Target confidence for role readiness",
    )
    gap: float = Field(..., description="required - current confidence")
    priority: PriorityEnum = Field(
        ...,
        description="Gap priority: high, medium, or low",
    )
    role_relevance: float = Field(
        ...,
        description="How important this competency is for target role",
    )
    recommended_action: str = Field(
        ...,
        description="One-line action to address this gap",
    )


class SkillGraphNode(BaseModel):
    """A single node in the skill confidence graph visualization."""

    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Competency id")
    label: str = Field(..., description="Display label")
    confidence: float = Field(..., description="Current confidence 0.0-1.0")
    color: str = Field(
        ...,
        description="Visualization color: red < 0.4, yellow 0.4-0.7, green > 0.7",
    )
    size: int = Field(default=20, description="Node size for visualization")
    parent: Optional[str] = Field(default=None, description="Parent node id")


class SkillGraphEdge(BaseModel):
    """A directed edge in the skill graph showing dependency."""

    model_config = ConfigDict(frozen=True)

    source: str = Field(..., description="Source competency id (prerequisite)")
    target: str = Field(..., description="Target competency id (depends on source)")
    relationship: str = Field(
        default="prerequisite",
        description="prerequisite, related, or advanced_of",
    )
    strength: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Relationship strength 0.0-1.0",
    )


class SkillGraph(BaseModel):
    """Complete skill graph for a user, ready for visualization."""

    model_config = ConfigDict(frozen=True)

    user_id: int = Field(..., description="User this graph belongs to")
    nodes: list[SkillGraphNode] = Field(
        default_factory=list,
        description="All competency nodes",
    )
    edges: list[SkillGraphEdge] = Field(
        default_factory=list,
        description="All dependency edges",
    )
    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When this graph snapshot was generated",
    )
