"""
Recommendation schemas.

Output contracts from the recommendation pipeline.
Every recommendation is tied to a specific competency gap.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class ResourceType(str, Enum):
    """Type of learning resource."""

    DOCUMENTATION = "documentation"
    COURSE = "course"
    ARTICLE = "article"
    PRACTICE = "practice"
    BOOK = "book"
    VIDEO = "video"


class Resource(BaseModel):
    """A single learning resource linked to a competency."""

    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Resource identifier")
    title: str = Field(..., description="Resource title")
    url: str = Field(..., description="Resource URL")
    resource_type: ResourceType = Field(..., description="Type of resource")
    difficulty: str = Field(
        default="intermediate",
        description="beginner, intermediate, or advanced",
    )
    competency_ids: list[str] = Field(
        default_factory=list,
        description="Which competencies this resource addresses",
    )
    description: str = Field(
        default="",
        description="Brief description of what this resource covers",
    )


class Recommendation(BaseModel):
    """
    A single personalized learning recommendation.

    Generated by the recommendation engine based on
    identified skill gaps and competency scores.
    """

    model_config = ConfigDict(frozen=False)

    id: str = Field(..., description="Unique recommendation identifier")
    user_id: int = Field(..., description="User this recommendation is for")
    session_id: int = Field(
        ...,
        description="Session that triggered this recommendation",
    )
    competency_id: str = Field(
        ...,
        description="Which competency gap this addresses",
    )
    competency_name: str = Field(..., description="Human-readable competency name")
    title: str = Field(..., description="Recommendation title")
    description: str = Field(..., description="Why this is recommended")
    resource: Optional[Resource] = Field(
        default=None,
        description="Linked learning resource if applicable",
    )
    priority: str = Field(
        default="medium",
        description="high, medium, or low priority",
    )
    week_number: int = Field(
        default=1,
        ge=1,
        description="Which week of the learning roadmap this belongs to",
    )
    estimated_hours: float = Field(
        default=2.0,
        description="Estimated learning time in hours",
    )
    is_completed: bool = Field(
        default=False,
        description="Whether user marked this complete",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When this recommendation was generated",
    )
    completed_at: Optional[datetime] = Field(
        default=None,
        description="When user marked this complete",
    )


class WeeklyPlan(BaseModel):
    """A single week in the personalized learning roadmap."""

    model_config = ConfigDict(frozen=True)

    week_number: int = Field(..., description="Week number starting from 1")
    focus_competency: str = Field(
        ...,
        description="Primary competency to focus on this week",
    )
    focus_competency_name: str = Field(..., description="Human-readable name")
    recommendations: list[Recommendation] = Field(
        default_factory=list,
        description="Learning tasks for this week",
    )
    estimated_hours: float = Field(
        default=0.0,
        description="Total estimated hours for this week",
    )
    goal: str = Field(
        ...,
        description="What the user should be able to do by end of week",
    )


class LearningRoadmap(BaseModel):
    """
    Complete personalized learning roadmap for a user.

    Generated after each interview session based on
    identified skill gaps ordered by priority and dependency.
    """

    model_config = ConfigDict(frozen=False)

    user_id: int = Field(..., description="User this roadmap belongs to")
    session_id: int = Field(
        ...,
        description="Session that triggered roadmap generation",
    )
    target_role: str = Field(..., description="Target job role")
    total_weeks: int = Field(..., description="Total weeks in the roadmap")
    weekly_plans: list[WeeklyPlan] = Field(
        ...,
        description="Week by week learning plan ordered by priority",
    )
    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When this roadmap was generated",
    )
    estimated_readiness_date: Optional[str] = Field(
        default=None,
        description="Estimated date user will be interview-ready",
    )
